name: Skypixel
favicon: null
layout_spectrum: 0.27049
typography_spectrum: 0.8916
title: Skypixel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e2953'
    - '#c3caca'
    - '#77818a'
    - '#535d65'
    - '#eff3f5'
  brandStrength: 0.875
  lightness: 0.7579530072398484
  saturation: 1
  rhythmicContrast: 1
purpose: []
