name: Skypixel
favicon: null
layout_spectrum: 0.75398
typography_spectrum: 0.617491704178974
title: Skypixel everything for drones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.625
  lightness: 0.7579530072398484
  saturation: 0.3126113147009164
  rhythmicContrast: 0.8073570202104747
purpose: []
